services:
  bot:
    build:
      dockerfile: Dockerfile
    container_name: language-bot
    volumes:
      - ./:/app
      - .env:/app/.env
      - data:/app/data
    ports:
      - '8910:80'  # replace 8080 with a rare port if desired
    working_dir: /app
    command: python run_telegram.py

volumes:
  data:
    driver: local
