services:
  bot:
    build:
      dockerfile: Dockerfile
    container_name: language-bot
    volumes:
      - ./:/app
      - .env:/app/.env
      - ./data:/app/data
    ports:
      - "${BOT_EXT_PORT:-80}:80"
    working_dir: /app
    command: python run_telegram.py
