"""Add peg tracing

Revision ID: 1eeb1a1b6a1f
Revises: ca52cef0c292
Create Date: 2025-10-15 17:44:02.279694

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "1eeb1a1b6a1f"
down_revision = "ca52cef0c292"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("slot_execution_logs", if_exists=True)
    with op.batch_alter_table("emitted_signals", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("peg_trigger_id", sa.Integer(), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("emitted_signals", schema=None) as batch_op:
        batch_op.drop_column("peg_trigger_id")

    op.create_table(
        "slot_execution_logs",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("emitted_signal_id", sa.INTEGER(), nullable=False),
        sa.Column("slot_name", sa.VARCHAR(), nullable=False),
        sa.Column("status", sa.VARCHAR(), nullable=False),
        sa.Column("started_at", sa.DATETIME(), nullable=False),
        sa.Column("duration_ms", sa.INTEGER(), nullable=False),
        sa.Column("error_message", sa.VARCHAR(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        if_not_exists=True,
    )
    # ### end Alembic commands ###
