"""empty message

Revision ID: 2b08e6acf3a6
Revises: e640d6c87c58
Create Date: 2025-05-28 02:32:33.249132

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b08e6acf3a6'
down_revision = 'e640d6c87c58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('views', schema=None) as batch_op:
        batch_op.alter_column('ts_review_finished',
               existing_type=sa.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('views', schema=None) as batch_op:
        batch_op.alter_column('ts_review_finished',
               existing_type=sa.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###
