"""Added polymorphic fields to notes and cards

Revision ID: ac5e7d079c94
Revises: c986644ee621
Create Date: 2025-07-25 13:14:49.351413

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ac5e7d079c94"
down_revision = "c986644ee621"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("cards", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "type",
                sa.String(length=50),
                nullable=False,
                server_default="card",
            )
        )

    with op.batch_alter_table("notes", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "type",
                sa.String(length=50),
                nullable=False,
                server_default="note",
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("notes", schema=None) as batch_op:
        batch_op.drop_column("type")

    with op.batch_alter_table("cards", schema=None) as batch_op:
        batch_op.drop_column("type")

    # ### end Alembic commands ###
