"""
Revision ID: bbe1095b83f1
Revises: eae042d2e15e
Create Date: 2025-08-02 17:25:03.666559

"""

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utc


# revision identifiers, used by Alembic.
revision = "bbe1095b83f1"
down_revision = "eae042d2e15e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("cards", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "ts_created",
                sqlalchemy_utc.sqltypes.UtcDateTime(timezone=True),
                nullable=False,
                server_default=sa.func.now(),
            )
        )

    with op.batch_alter_table("notes", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "ts_created",
                sqlalchemy_utc.sqltypes.UtcDateTime(timezone=True),
                nullable=False,
                server_default=sa.func.now(),
            )
        )
    # ### end Alembic commands ###
    op.execute("UPDATE notes SET type = 'word_note'")


def downgrade():
    op.execute("UPDATE notes SET type = 'note' WHERE type = 'word_note'")
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("notes", schema=None) as batch_op:
        batch_op.drop_column("ts_created")

    with op.batch_alter_table("cards", schema=None) as batch_op:
        batch_op.drop_column("ts_created")

    # ### end Alembic commands ###
