"""Add indexes to cards, notes, views

Revision ID: ca52cef0c292
Revises: bbe1095b83f1
Create Date: 2025-10-10 23:14:54.059446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca52cef0c292'
down_revision = 'bbe1095b83f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cards_note_id'), ['note_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cards_ts_scheduled'), ['ts_scheduled'], unique=False)

    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notes_language_id'), ['language_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notes_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('views', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_views_card_id'), ['card_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_views_ts_review_finished'), ['ts_review_finished'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('views', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_views_ts_review_finished'))
        batch_op.drop_index(batch_op.f('ix_views_card_id'))

    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notes_user_id'))
        batch_op.drop_index(batch_op.f('ix_notes_language_id'))

    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cards_ts_scheduled'))
        batch_op.drop_index(batch_op.f('ix_cards_note_id'))

    # ### end Alembic commands ###
