"""empty message

Revision ID: e640d6c87c58
Revises: 
Create Date: 2025-05-26 05:00:53.366215

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e640d6c87c58'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stability', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('difficulty', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('ts_last_review', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('ts_scheduled', sa.DateTime(), nullable=False))

    with op.batch_alter_table('views', schema=None) as batch_op:
        batch_op.drop_column('ts_scheduled')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('views', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ts_scheduled', sa.DATETIME(), nullable=False))

    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.drop_column('ts_scheduled')
        batch_op.drop_column('ts_last_review')
        batch_op.drop_column('difficulty')
        batch_op.drop_column('stability')

    # ### end Alembic commands ###
